### ISSUE TITLE
+X and +Y directions need latitude coordinate

### ISSUE THREAD

**Issue by MBARIMike** [MBARIMike/papers#16]
In subsection "The geocentric coordinate system"

Perhaps add "at equator", or "in equatorial plane" for direction of +X and +Y axes. Also, +Y is at 90 degrees **east**, correct?

**Comment by andreasplesch** [comment]
In section 4.1 ? Yes, this would help although not strictly necessary since
the sentence before just establishes that the origin is at the center.
What about:
"In the equatorial plane, the +X direction points to 0 degrees longitude
and the +Y direction to 90 degrees longitude east. The +Z direction points
to the north pole."

On Tue, Mar 17, 2015 at 2:59 PM, Mike McCann notifications@github.com
wrote:

> Perhaps add "at equator", or "in equatorial plane" for direction of +X and
> +Y axes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MBARIMike/papers/issues/16.

## 

Andreas Plesch
39 Barbara Rd.
Waltham, MA 02453

**Comment by MBARIMike** [comment]
See ftp://ftp.mbari.org/pub/mccann/X3DGeospatialComponent.pdf
